import Head from 'next/head';
import Image from 'next/image';
import GlobalStyle from '../components/globalstyles';
import HeaderMain from '../components/header/headerMain';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <GlobalStyle />
      <HeaderMain />
      <main>
        <h1>Hello world</h1>
      </main>
    </>
  )
}
